services:
  journals-backend:
    ports:
      - "8080:8080"
    environment:
      APP_NAME: "Journals Backend"
      APP_ENV: local
      APP_KEY: base64:4TAXryRoh2UAJ+3CTEi8+IgKArhnKv/cOcBWmeUex3E=
      APP_DEBUG: "true"
      APP_URL: http://jorunals.local

      USER_ROOT_EMAIL: "admin@cit-sk.ru"
      USER_ROOT_PASSWORD: "admin1234"
      USER_ROOT_LAST_NAME: "Admin"
      USER_ROOT_FIRST_NAME: "Admin"
      USER_ROOT_POST: "Admin"

      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: journals_db
      DB_USERNAME: user
      DB_PASSWORD: pass

      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_CACHE_DB: 1
      CACHE_DRIVER: redis
      SESSION_DRIVER: cookie
      QUEUE_CONNECTION: redis

      SANCTUM_STATEFUL_DOMAINS: localhost:5173, journals.local
      SESSION_DOMAIN: .journals.local

      XDEBUG: "1"
    volumes:
      - .:/var/www/html
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: journals_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U journals_user -d journals_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ""
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
